### ISSUE TITLE
接入的SDK 3.1.1 http://c.data.mob.com/v3/cdata 此接口超时很严重

### ISSUE THREAD

**Issue by hloong** [MobClub/ShareSDK-for-Android#16]
如下图所示，每天不胜其烦，这个接口能不能屏蔽掉？貌似iOS不出现这种问题

![qq 20180507160741](https://user-images.githubusercontent.com/3353954/39691703-fd114f6e-5210-11e8-9599-093a2913aa14.jpg)
![qq 20180507160811](https://user-images.githubusercontent.com/3353954/39691708-ff0eefe2-5210-11e8-8f74-092e9e0d3185.jpg)
![qq 20180507160847](https://user-images.githubusercontent.com/3353954/39691715-00d40a42-5211-11e8-8f30-7776b2c471c9.jpg)

**Comment by moblarry** [comment]
这个是服务器的接口的问题导致的，不过不影响SDK的使用与分享的，现早已优化
