### ISSUE TITLE
资源冲突

### ISSUE THREAD

**Issue by beautifulSoup** [MobClub/ShareSDK-for-Android#39]
5月29日下午4点之后突然编译报错。通过git reset 到之前的代码还是如此。
提示资源冲突，截图如下：
![image](https://user-images.githubusercontent.com/5506713/83246377-9dc08500-a1d4-11ea-8960-7155d376af7a.png)

**Comment by yuwenjian** [comment]
你好，可以添加下这个
`buildscript {
    repositories {
        maven { url "http://mvn.mob.com/android"}
        jcenter()
        google()
         maven { url'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
         maven { url "https://maven.google.com" }
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.3'
        classpath 'com.mob.sdk:MobSDK:+'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }

    configurations.all {
        resolutionStrategy.cacheDynamicVersionsFor 1, 'seconds'
    }
}

allprojects {
    repositories {
        maven { url "http://mvn.mob.com/android"}
        jcenter()
        google()
      maven { url'http://maven.aliyun.com/nexus/content/repositories/jcenter' }
        maven { url "https://maven.google.com" }

    }
    configurations.all {
        resolutionStrategy.cacheDynamicVersionsFor 1, 'seconds'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

主要是：
`  configurations.all {
        resolutionStrategy.cacheDynamicVersionsFor 1, 'seconds'
    }`

**Comment by beautifulSoup** [comment]
好的，我试下

**Comment by beautifulSoup** [comment]
Thank you. its resolved.

**Comment by beautifulSoup** [comment]
你好，又出现这个问题了，又是这个时间点，崩溃

**Comment by beautifulSoup** [comment]
@yuwenjian

**Comment by beautifulSoup** [comment]
望处理解决啊，明天就要发版了，没法编译，鸭梨山大啊 @yuwenjian

**Comment by beautifulSoup** [comment]
加了微信终于得到了解答 原因是ShareSdk 和OneKeyShare 资源冲突，需要强制制定下ShareSdk版本。
![image](https://user-images.githubusercontent.com/5506713/83472773-9d690800-a4ba-11ea-98a5-c31877776e69.png)
