### ISSUE TITLE
微博分享报错

### ISSUE THREAD

**Issue by FOnlyJack** [MobClub/ShareSDK-for-Android#47]
mob最新版 
Android 10

java.lang.Throwable: errorCode: 2 errorMessage: msg is null!!!! errorDetail: error from weibo client!

**Comment by linhua55** [comment]
就算进行图片分享，也必须加上文字，空格也行。
 shareParams.setText(" ");

如果进行图片分享，这个demo项目 可能是权限的问题，并不能分享相机目录下的图片。只能先把图片复制到 mContext.getExternalCacheDir() ，外部缓存目录下，然后再分享缓存目录下的图片。

图片路径不能含有中文

这是我测试出来的情况。
